### ISSUE TITLE
RecyclerView inside ZoomLayout

### ISSUE THREAD

**Issue by vivekav-96** [natario1/ZoomLayout#10]
When placing RecyclerView inside ZoomLayout, the whole recyclerView is shown.
```
@Override
      public void onGlobalLayout() {
               mChildRect.set(0, 0,
                       child.getWidth(),
                       child.getHeight());
               mEngine.setContentSize(mChildRect);
       }
});
super.addView(child, index, params);
```

Can anything be done to change this behavior? Just to implement a preview view like Google Drive.

**Comment by natario1** [comment]
What screen of Google Drive exactly? I'm not sure I know what you mean.

Maybe you are just looking for `app:minZoom="1"`.

**Comment by vivekav-96** [comment]
![screenshot_20171028-195801 1](https://user-images.githubusercontent.com/25697839/32100067-566d2dee-bb30-11e7-8f8f-5360f8e93fa0.png)

Open a pdf file to preview in Google Drive and you'll see the below screen.

How to create a view like this with ZoomLayout? I guess it is a RecyclerView inside a zoomable layout (just like ZoomLayout).

**Comment by natario1** [comment]
ZoomLayout will load the whole view so there's no need for RecyclerView. Just use a vertical LinearLayout. And set minZoom to 1.

I have a project doing this https://github.com/natario1/ViewPrinter take a look.

**Comment by vivekav-96** [comment]
I am loading pages in recyclerview dynamically.

I want to make the whole RecyclerView zoomable. I've also tried your DocumentView in your [other project](https://github.com/natario1/ViewPrinter). Great stuff actually.

Can you help me? thank you :)

**Comment by natario1** [comment]
I don't know if we support RecyclerView. Make sure to set height="wrap_content" and probably also app:nestedScrollingEnabled="false" to the recycler. And then you should play with minZoom APIs to get the desired min zoom

**Comment by vivekav-96** [comment]
I did make the RecyclerView zoomable using ZoomEngine.

But On Scaling, the RecyclerView flickers.

**Comment by natario1** [comment]
If you have a repro project here on GitHub I can take a look in the next days, but it's possible that we don't support it. ZoomLayout has its own scrolling mechanism so you should not put scrollable views inside

**Comment by vivekav-96** [comment]
Can I contact you personally by email for this? Please

**Comment by rishabhAlgoworks** [comment]
@vivekav-96 were you able to make a recycler-view zoomable?

**Comment by rishabhAlgoworks** [comment]
@vivekav-96 were you able to make the recyclerview zoomable?

**Comment by rishabh-2493** [comment]
@vivekav-96 were you able to make the recycler-view zoomable? Help please.
