### ISSUE TITLE
DEFAULT_OVERZOOM_FACTOR customizable

### ISSUE THREAD

**Issue by diana2201** [natario1/ZoomLayout#100]
Hi!
Is there any way to set up the `DEFAULT_OVERZOOM_FACTOR` in order to increase the zoom animation when `overPinchable`is true?

**Comment by natario1** [comment]
Nope, there is no way to do this at the moment

**Comment by markusressel** [comment]
@natario1  it should be pretty easy to add  this  though, right?

**Comment by natario1** [comment]
Yes! If some of you want to work on it... I would not expose the factor but rather the whole function. 

I think it currently is (maxZoom - minZoom) * factor. This is not necessarily good for all cases, for example if min=max you can never overzoom.

So we should create an interface like OverZoomRangeProvider and add the API setOverZoomRange(provider). The only method in the interface would then be getOverZoomRange(engine).

The default provider should then do (maxZoom - minZoom) * 0.1 like we currently do. The engine will need public getters for these.

The same could be done with OverPan I guess
