### ISSUE TITLE
Allow pan with only two or more fingers

### ISSUE THREAD

**Issue by RayyanTahir** [natario1/ZoomLayout#101]
I'm writing a screen sharing/viewing app like teamviewer where I can control the remote stream, I have the mouse movement set up with single finger pan, but with this library attached the image pans as well. Is there a way to only allow panning when two or more fingers are used?

Any kind of help will be appreciated. Thanks

**Comment by natario1** [comment]
There is no option for this at the moment, sorry! If you want to work on it, it would be cool to have two attributes, `scrollEnabled` (generic but currently missing) and `singleFingerScrollEnabled` (which you could then disable).

**Comment by RayyanTahir** [comment]
Thank you, I could give it a shot and come up with a PR maybe?

**Comment by natario1** [comment]
That would be cool! Thank you!
