### ISSUE TITLE
newly added scrollEnabled, oneFingerScrollEnabled, twoFingersScrollEnabled, and threeFingersScrollEnabled attributes not found

### ISSUE THREAD

**Issue by jamneeley** [natario1/ZoomLayout#104]
error: attribute oneFingerScrollEnabled (aka com.example.test.zoomlayouttest:oneFingerScrollEnabled) not found.
error: attribute scrollEnabled (aka com.example.test.zoomlayouttest:scrollEnabled) not found.
error: attribute threeFingersScrollEnabled (aka com.example.test.zoomlayouttest:threeFingersScrollEnabled) not found.
error: attribute twoFingersScrollEnabled (aka com.example.test.zoomlayouttest:twoFingersScrollEnabled) not found.

**Comment by markusressel** [comment]
I don't think this has been released yet.

**Comment by jamneeley** [comment]
ahhh that makes sense. I should have looked a little closer. Thanks

**Comment by RayyanTahir** [comment]
@jamneeley since this isn't released yet, you can use https://jitpack.io/ to get the library with that feature in your project.

**Comment by chitra-bahadur** [comment]
Hi any update on above issue i am also facing same issue

**Comment by markusressel** [comment]
I'm not sure about the current state of master and if it should be released in it's current form.
@natario1 You did some refactoring a while ago, is there any necessary work left before a new version  with the feature mentioned in here can be released?

**Comment by natario1** [comment]
No, everything is ready AFAIR, I am just traveling 🙄 will do as soon as I can! Or you can do it, following what I did for latest releases (bump versions, log changes in changelog with credits, create GitHub release...)

**Comment by markusressel** [comment]
@chitra-bahadur @jamneeley @RayyanTahir 
1.6.1 has now been released:
https://github.com/natario1/ZoomLayout/releases/tag/v1.6.1
