### ISSUE TITLE
ZoomLayout not zooming when added a framelayout inside Zoomlayout.

### ISSUE THREAD

**Issue by Samyak81** [natario1/ZoomLayout#109]
I have store rack kind off view in which i am adding multiple views based on coordinate and need to Zoom it. So i added all the views based on coordinates in ZoomView and add that zoomview in Framelayout. But my concern is now the Zoom feature and pan feature is not working of Zoomlayout

**Comment by markusressel** [comment]
Can you provide a demo project for this issue to reproduce it?
