### ISSUE TITLE
PanTo position coordinates have to be negative?

### ISSUE THREAD

**Issue by Armijn** [natario1/ZoomLayout#11]
First of all, thank you for this amazing library.
Maybe it's just me or I didn't get it, but when I used `panTo` and passed in the X and Y position of a child it would just scroll to the top left, it turned out that it had to be the negative value of the child, I find this a bit confusing, and it took me a while to figure it out.

**Comment by natario1** [comment]
Thanks for your words. It's as you say.

I don't like it either, but

- it's consistent with Android behavior, e.g. a Matrix scale type for an ImageView, or even setTranslation if you think about it
- changing this would require a major release

**Comment by markusressel** [comment]
Imo it's more than desirable to be consistent with Android behavior and changing it would give no real benefit. I added a note about it to the README though.
