### ISSUE TITLE
ZoomLayout not zooming for CardView in Android 9 Pie

### ISSUE THREAD

**Issue by leonardusirfan** [natario1/ZoomLayout#110]
I can't get my ZoomLayout work on Android 9 Pie, or im doing it wrong?
This is my XML 

    <com.otaliastudios.zoom.ZoomLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical|horizontal"
        app:overScrollHorizontal="true"
        app:overScrollVertical="true"
        app:overPinchable="true"
        app:horizontalPanEnabled="true"
        app:verticalPanEnabled="true"
        app:zoomEnabled="true"
        app:hasClickableChildren="false">

        <android.support.v7.widget.CardView
            android:id="@+id/layout_galeri_selected"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:cardCornerRadius="@dimen/padding5">

            <ImageView
                android:id="@+id/img_galeri_selected"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:contentDescription="@string/artis"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toStartOf="@+id/btn_next"
                app:layout_constraintStart_toEndOf="@+id/btn_previous"
                app:layout_constraintTop_toTopOf="parent"/>

        </android.support.v7.widget.CardView>
    </com.otaliastudios.zoom.ZoomLayout>

and i load my image into ImageView inside it like this

```
Glide.with(this)
  .load(listImage.get(selectedImage))
  .transition(DrawableTransitionOptions.withCrossFade())
  .apply(new RequestOptions()
  .override(imgWidth, imgHeight)
  .placeholder(new ColorDrawable(Color.TRANSPARENT))
  .diskCacheStrategy(DiskCacheStrategy.NONE))
  .into(img_galeri_selected);
```
 @RayyanTahir

**Comment by leonardusirfan** [comment]
I think it is because of the CardView. When I remove the CardView, and put the ImageView as its direct child, ZoomLayout works properly.

**Comment by markusressel** [comment]
First, I reformatted your question because it was broken and not very readable.
Second, Your issue description is lacking important information.
What exactly is the issue?
Do you get an exception?
Is the view invisible?
Does zooming/scrolling not work?

**Comment by leonardusirfan** [comment]
Thanks for your help @markusressel, so I'll try to clarify my issue here.
I actually didn't realize it at first, but the ZoomLayout is not zooming only if its **direct child is CardView** (or MaterialCardView) and on **Android 9 Pie** (I have no issue for android 8 and below using the same xml). Then there is no exception. About the runtime view, it is visible but its position is off, also the scrolling and zooming isn't work at all. I put some screenshot here to give clearer picture about how the runtime view would be on my phone.

![zoomlayout3](https://user-images.githubusercontent.com/41319237/60856288-d6f4ad00-a230-11e9-95ef-f2a98af95293.jpg)
![zoomlayout1](https://user-images.githubusercontent.com/41319237/60856289-d6f4ad00-a230-11e9-8e90-5aa808df84a8.jpg)

**Comment by markusressel** [comment]
ZoomLayout only supports a single child. Did you try wrapping the ```CardView``` in a simpler layout like a ```LinearLayout``` or something similar?

**Comment by leonardusirfan** [comment]
wow i didn't think about that and it works! zooming and scrolling works like normal.

So i think the problem only occur if its direct child is CardView. Even wrapped CardView doesn't make it occur.

**Comment by markusressel** [comment]
Great :+1: 
Afaik ```CardView``` does a lot of layout magic, especially when using compatibility mode. I guess this interferes with the way the ```ZoomLayout```engine works. I don't think there is much we can do about this so I think just wrapping it - although maybe unfulfilling - is a good enough solution.
I will close this issue for now but feel free to reopen it if this issue comes up again.
