### ISSUE TITLE
DoubleTap zoom to the touched position

### ISSUE THREAD

**Issue by brunogalerani** [natario1/ZoomLayout#112]
Hello,

First of all, thank you for creating this API. It's really helping me!

I'm trying to implement a DoubleTap to zoom that zooms in to the exact point I've touched.

I've tried using imageView.panTo(zoom, x, y, true), but it looks like that it aways zoom in to the same point for every value that I pass in "x" and "y" parameters.

If I pass 0,0, it zooms in to the top corner of the image and if I pass 600, 600 it goes to the same point.

Is there anyway to make this kind of interaction work?

Thank you in advance!

**Comment by markusressel** [comment]
I think you need to use negativ coordinate values.

**Comment by brunogalerani** [comment]
I'm tryng to make ti Zoom to the point I've touched by getting the getX and getY from the MotionEvent parameter. How would I use it with negative coordinates and get the right spot in the image?

**Comment by markusressel** [comment]
Well, you have to take the screen coordinate and map it to the location of the `ZoomLayout` canvas. If the `MotionEvent` coordinates are already using the correct coordinate system they should have the correct sign.

I implemented a minimap in my [KodeEditor](https://github.com/markusressel/KodeEditor) project which allows the user to tap the minimap to scroll the full view. For this I wrote a method to move the canvas to a given x- and y-percentage. You can have a look at how I have done this here:
https://github.com/markusressel/KodeEditor/blob/675bdfd7160139e83b38de9ad83f1bc6e113f734/library/src/main/java/de/markusressel/kodeeditor/library/view/CodeEditorLayout.kt#L376

Also have a look at where this method is used to understand how I calculated the percentages:
https://github.com/markusressel/KodeEditor/blob/675bdfd7160139e83b38de9ad83f1bc6e113f734/library/src/main/java/de/markusressel/kodeeditor/library/view/CodeEditorLayout.kt#L312

Although this is not exactly what you want to do I hope it helps to understand how to calculate view coordinates.

**Comment by brunogalerani** [comment]
Thank you for sending some reference!
I'll try to get this working now.
