### ISSUE TITLE
Not working inside recycler view

### ISSUE THREAD

**Issue by saranyalekshmanan** [natario1/ZoomLayout#115]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@color/colorIcons"
    android:layout_margin="@dimen/_4dp">

    <androidx.appcompat.widget.AppCompatImageView
        android:layout_width="match_parent"
        android:layout_height="300dp"
        android:id="@+id/thumpnail"
        android:scaleType="fitXY"
        android:layout_margin="20dp"
        android:scrollbars="vertical|horizontal"
        app:transformation="centerInside"
        app:transformationGravity="auto"
        app:alignment="center"
        app:overScrollHorizontal="true"
        app:overScrollVertical="true"
        app:overPinchable="false"
        app:horizontalPanEnabled="true"
        app:verticalPanEnabled="true"
        app:zoomEnabled="true"
        app:flingEnabled="true"
        app:scrollEnabled="true"
        app:oneFingerScrollEnabled="true"
        app:twoFingersScrollEnabled="true"
        app:threeFingersScrollEnabled="true"
        app:minZoom="1"
        app:minZoomType="zoom"
        app:maxZoom="2.5"
        app:maxZoomType="zoom"
        app:animationDuration="280"
        />

</LinearLayout>

Here is my item layout of recycler view
Please help this to get out of this

**Comment by markusressel** [comment]
You specify an `androidx.appcompat.widget.AppCompatImageView` component which has nothing to do with **ZoomLayout**. Maybe you want to use `com.otaliastudios.zoom.ZoomImageView`?
