### ISSUE TITLE
Nested ZoomLayout

### ISSUE THREAD

**Issue by TeSchaefer** [natario1/ZoomLayout#119]
Hey everyone,

first of all.. Thank you for this great API.
But i'm struggling with the layouts by using them in a nested way.
Is there an easy way to solve that problem?

I'm currently using the ZoomLayout within a SwipeRefreshLayout and can't scroll-up within the ZoomLayout without triggering the refresh method..

**Comment by markusressel** [comment]
Sorry, but this is not supported. If you find a workaround feel free to post it here.

**Comment by Tomas13** [comment]
@TeSchaefer I had a similar issue with ScrollView, so I decided to zoom with two fingers and interact with the scrollView with one finger. Here's a simple solution for that https://stackoverflow.com/a/65923647/3847464
