### ISSUE TITLE
Trying to calculate x and y coordinates

### ISSUE THREAD

**Issue by np161** [natario1/ZoomLayout#120]
I am trying to get the x and y points to add a button at those points. 

((event.rawX - scaledPanX) * (1/realZoom)).toInt() 
((event.rawY - scaledPanY) * (1/realZoom)).toInt() 

Is what i am doing to get the coordinates when zoomed in but the x value seems to off. Everytime the button is added slighltly to the right of where I press. The y coordiante is fine. Is this the correct way to get these values

**Comment by JeffZane** [comment]
i have the same question

**Comment by JeffZane** [comment]
i have the same question
