### ISSUE TITLE
Child GetGlobalVisibleRect not working when hasClickableChildren is flase

### ISSUE THREAD

**Issue by sgravel-dev** [natario1/ZoomLayout#126]
I'm using the following code to determine the screen position of a ZoomLayout children :
```
Rect viewRect = new Rect();

if (OriginatingView.GetGlobalVisibleRect(viewRect))
{
    var location = new int[2];

    OriginatingView.GetLocationOnScreen(location);
    viewRect.OffsetTo(location[0], location[1]);
                        
    _originatingViewRect = viewRect;
}
```

However `GetGlobalVisibleRect` doesn't return the right screen coordinates if children are not marked as clickable.

P.S. `GetLocationOnScreen` is necessary for when the ZoomLayout is nested within a `DialogFragment` as `GetGlobalVisibleRect` returns the coordinates within the dialog which is not always full screen.

**Comment by sgravel-dev** [comment]
Still relevant

**Comment by natario1** [comment]
Just use hasClickableChildren=true :-) hasClickableChildren=false is a more efficient setup that won't fit all use cases.
