### ISSUE TITLE
ZoomSurfaceView Not working with Exoplayer PlayerView

### ISSUE THREAD

**Issue by vipinhelloindia** [natario1/ZoomLayout#128]
Try Cloning the Exo Player sample and replace the Surfaceview with zoom view

**Comment by Anatolf** [comment]
Hi. Tell me if there is some way to use exoplayer2 in ZoomLayout.
With fixed layout_width and layout_height in com.google.android.exoplayer2.ui.PlayerView - ZoomLayout does not work correctly.
In other cases it does not work at all.

**Comment by Anatolf** [comment]
Everything works fine even with new exoplayer2 by google.
Use ZoomSurfaceView as in the sample application demo.
