### ISSUE TITLE
Q: Overlay view

### ISSUE THREAD

**Issue by riki-dexter** [natario1/ZoomLayout#13]
Hi @natario1,
I'd like to create a colors grid with your ZoomLayout.
I can easily build the grid using a class that extends GridLayout like in your example class ColorGridView.
But how can i add a view in overlay like in attached screenshot over tapped view in grid?

Thank you!
![foto 08-02-18 15 26 04](https://user-images.githubusercontent.com/1485097/35978175-4b055d80-0ce5-11e8-8dd7-1f0c688e9d75.png)

**Comment by natario1** [comment]
Hi!

If the overlay is supposed to move with the content, then it must be part of the content, you know, part of the view.
 
When developing, try to reach your desired result *without* ZoomLayout. When it works (without scrolling), then put everything inside the ZoomLayout, and you'll have scrolling behavior too. But that is the last step.

**Comment by riki-dexter** [comment]
So you think that I have to develop my own view, that responds to user tap and on tap it show the other view overlay. 
Adding this view to ZoomLayout i will have scrolling behavior of the grid of views, but each view will have overlay effect on click.
Right?
Thank you.

**Comment by natario1** [comment]
That's it! ZoomLayout is just a scrolling container.

**Comment by riki-dexter** [comment]
Ok, thank you!

**Comment by riki-dexter** [comment]
Ok, thank you!
