### ISSUE TITLE
how to use it with dinamic content

### ISSUE THREAD

**Issue by zsolt023** [natario1/ZoomLayout#134]
Hello, i want to use ZoomLayout with two [PDFView](https://github.com/barteksc/AndroidPdfViewer)s inside it, to be able to zoom the two PDFs together.

After loading the two PDFs programmatically, they does not even appear in the screen. Zooming at this point isn't working at all. How can i force the zoomview (after loading PDFs) to redraw itself? (I tried invalidate() and invalidate() with a couple of seconds after PDF loadings.)

Here is the code:

    <com.otaliastudios.zoom.ZoomLayout
        android:id="@+id/zoom_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="horizontal">

            <com.github.barteksc.pdfviewer.PDFView
                android:id="@+id/pdf_view_1"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

            <com.github.barteksc.pdfviewer.PDFView
                android:id="@+id/pdf_view_2"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />
        </LinearLayout>
    </com.otaliastudios.zoom.ZoomLayout>

lib v: 1.7.0
PDF lib v: 2.8.2

**Comment by natario1** [comment]
Dynamic content is not a problem, but it is possible that your `PDFView` does not work well inside a ZoomLayout.

**Comment by zsolt023** [comment]
Thoose PDFView-s are zoomable themself, may is this the problem?
