### ISSUE TITLE
ZoomImageView doesn't initially pan to center of the bitmap

### ISSUE THREAD

**Issue by King-Henry** [natario1/ZoomLayout#135]
Hi,

Currently I'm using the ZoomImageView to crop images. (I add a grid view on top, then when I'm ready to finalize the crop, I'll use `zoomImageView.draw(canvas)` )

My ZoomImageView has a 1 to 1 ratio in terms of width and height and is contained within a ConstraintLayout as so:

`<com.otaliastudios.zoom.ZoomImageView
            android:id="@+id/zoom_image_view"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:visibility="invisible"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:transformation="centerCrop"
            app:transformationGravity="auto"
            app:alignment="center"
            app:overScrollHorizontal="true"
            app:overScrollVertical="true"
            app:overPinchable="true"
            app:horizontalPanEnabled="true"
            app:verticalPanEnabled="true"
            app:zoomEnabled="true"
            app:flingEnabled="true"
            app:scrollEnabled="true"
            app:oneFingerScrollEnabled="true"
            app:twoFingersScrollEnabled="true"
            app:threeFingersScrollEnabled="true"
            app:minZoom="1"
            app:minZoomType="zoom"
            app:maxZoom="5"
            app:maxZoomType="zoom"
            app:animationDuration="280"/>`

My flow I currently have is:

1. User takes photo with the camera that is the sensor resolution. (Let's say for example 3036x4048)
2. We put that picture into an ImageView with a scaleType of center crop
3. User goes into crop mode, where we hide the original ImageView and set the image bitmap on the ZoomImageView

For some reason when setting the image on the ZoomImageView, it doesn't pan to the center. It'll pan to the top, or bottom, but never the center regardless of what gravity or alignment I set.

Currently the only way I can get it to center when initially setting the bitmap is to first call `zoomImageView.setImageBitmap(bitmap)` then set the pan to `zoomImageView.panX / 2` and `zoomImageView.panY / 2`.  This seems to work when the width and height of the content are bigger than the container(zoomImageView), however when either the width or height of the content is smaller than the container, the panx and pany both end up being 0, so this solution doesn't work.

Am I doing something wrong here? Any help would be greatly appreciated.

**Comment by natario1** [comment]
You might want to try with `app:minZoom="0"`.

**Comment by King-Henry** [comment]
That didn't work unfortunately =(. It still jumps to the top or bottom/ left or right once I set the bitmap on the ZoomImageView. To put this whole thing in perspective, I was hoping to achieve an Instagram style cropping flow.

**Comment by natario1** [comment]
Can you tweak the demo app as little as possible so that it reproduces your issue?

**Comment by King-Henry** [comment]
Sure, I'll try and get it to you later today.

**Comment by natario1** [comment]
Other things you can try before that:
- use gone instead of invisible
- after you call `ziv.setImageBitmap(b)`, call `ziv.engine.setContentSize(b.width, b.height, true)`

**Comment by King-Henry** [comment]
Hey, just an update:  the 2 things above didn't work, so I'm currently in the process of trying to reproduce the issue on the demo app. I haven't been able to reproduce yet, so makes me wonder if it's something I'm doing in my app.

**Comment by King-Henry** [comment]
Hey, so I finally had some time to come back and check this out and I now have a tweaked version of the demo app. 

https://github.com/King-Henry/ZoomLayout-Centering-Issue

I've created a repro with the code that you should be able to use to repro the issues I'm having. The first image pans all the way to the left initially, the second image is okay, the third image pans to the top, and the fourth image is off center to the right.
