### ISSUE TITLE
Click on child is enabled even when disabled in xml

### ISSUE THREAD

**Issue by HozakaN** [natario1/ZoomLayout#137]
Steps to reproduce :
```
<com.otaliastudios.zoom.ZoomLayout
            android:id="@+id/zoom_layout"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:layout_margin="8dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/midGuideline"
            android:scrollbars="horizontal|vertical"
            app:hasClickableChildren="false"
            app:horizontalPanEnabled="false"
            app:verticalPanEnabled="false"
            app:zoomEnabled="false">

            <fr.hozakan.skylines.ui.ColorGridView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content" />

</com.otaliastudios.zoom.ZoomLayout>
```

![Screenshot 2020-01-26 at 05 47 29](https://user-images.githubusercontent.com/1032452/73130802-85aae000-3fff-11ea-929d-0b634de730da.png)

Touches where made in the circles (drawn on screen, not code modification), reflecting the touch as indicated, in a subset of the view, so I guess the issue is part due to matrix (since displaying touch at bad position but keeping ratio), part to a flag that should be updated/listened by the view.

Thank you for your work!

**Comment by natario1** [comment]
What is the issue? 
If you have clickable things inside the hierarchy you should use hasClickableChildren=true. If you don't, you can leave it false. In this case clicks might go to the wrong place but you won't care because you won't have clickable children.

**Comment by HozakaN** [comment]
The issue is : if clickable is marked at false, there should not be black square displaying. Thus Clickable is either false leading or false

**Comment by natario1** [comment]
Your views have a click listener so you should use hasClickableChildren=true . If you remove the click listener / black behavior from your view, then you can safely use hasClickableChildren=false

**Comment by HozakaN** [comment]
Can you just not dispatch touch events? Or use a non missleading name?

**Comment by natario1** [comment]
What name would you suggest? It sounds very good to me - you tell the layout if it **has** (or not) clickable children in it, which is something only the developer knows. It's not called enableClicks().

**Comment by HozakaN** [comment]
Ok maybe I should look at the code, but this name, for me, involves that touch event won't be dispatched, which is actually false. This is kind of a non-described convention.
I don't have a name for something that should not dispatch touch events but does unfortunnately

**Comment by HozakaN** [comment]
Can you validate or not the following assumption on your lib :
-ZoomLayout dispatches touch events

**Comment by HozakaN** [comment]
```
override fun onInterceptTouchEvent(ev: MotionEvent): Boolean {
        return engine.onInterceptTouchEvent(ev) || hasClickableChildren && super.onInterceptTouchEvent(ev)
    }
```

So it does. Here lies the problem. If clickable is false, even the engine should not receive those events.

**Comment by HozakaN** [comment]
Then maybe the name "dispatchTouchToChildren" would be better

**Comment by natario1** [comment]
As you have discovered, we always dispatch events (if hasClickableChildren=false, we dispatch at the wrong place, but still we dispatch). So the flag name `dispatch*=false` does not sound good to me.

About the feature itself, it is working as intended.

**Comment by HozakaN** [comment]
Then you should document this convention

**Comment by natario1** [comment]
That assumes you would read the documentation which does not seem to be the case. It's already there.

**Comment by HozakaN** [comment]
I've read it but I don't see any place you say touch event will be dispatched even with clickable = false.

I haven't been disobliging in my speech and would appreciate you do the same

**Comment by HozakaN** [comment]
I've read it and don't see anyplace where you tell clickable = false will still dispatch touch events.

I have not been disobliging, and would appreciate you act the same by being polite and not removing my posts

**Comment by markusressel** [comment]
Do you have a use-case in mind that would require the parent to stop propgating events to its children instead of the children just ignoring those events? As @natario1 said, the programmer controls all of the children. You can disable the click event processing on them already at free will. I think the purpose of the `hasClickableChildren` flag was just misunderstood and is not really related to the problem you may be trying to solve.
