### ISSUE TITLE
Zooming events

### ISSUE THREAD

**Issue by riki-dexter** [natario1/ZoomLayout#14]
Hi @natario1 ,
can you help me how to listen for zooming events of a ZoomLayout?
I'd like to be notified on views zoom level change, to do something when zoom level is over 2x for example.

Thank you!

**Comment by nikolamk** [comment]
me too

**Comment by natario1** [comment]
Right now, you must subclass ZoomLayout and override onUpdate / onIdle . Take a look at the source code for the class

**Comment by riki-dexter** [comment]
Yeah. I did it.
Thank you
