### ISSUE TITLE
 Recyclerview not visible in zoom layout

### ISSUE THREAD

**Issue by JSBDeveloper** [natario1/ZoomLayout#140]
`<com.otaliastudios.zoom.ZoomLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/viewer_recyclerview"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
        </com.otaliastudios.zoom.ZoomLayout>`

My code is not showing recyclerview
help :-(

**Comment by markusressel** [comment]
RecyclerView is not supported, see #87, #53
Also `match_parent` does not make sense, see #54
