### ISSUE TITLE
Vector drawable is pixelated when zooming in

### ISSUE THREAD

**Issue by SilvanaP** [natario1/ZoomLayout#142]
Hello, I am using zoom layout with an image view which displays a vector drawable / svg. So far, it works like a charm apart from one problem: when I set the max zoom to a high level, the vector drawable is pexelated when I zoom in.

Is this a known bug or is there some workaraound for this problem? Normally, vector drawables should be smooth on every zoom level - but maybe this is because of how zoom layout works internally? (I guess you use a bitmap to make the layout zoomable?)

**Comment by markusressel** [comment]
I would guess its due to the way the vector drawable is rendered. Even a vector graphic has to be rendered to a specific resolution at some point and it probably isn't rerendered when zooming. Maybe there is a way to actively redraw the vector drawable when the zoom level has changed?

**Comment by SilvanaP** [comment]
Ah, thanks, that's a great hint! Will try to find a way to trigger a redraw and report the outcome next week.

**Comment by SilvanaP** [comment]
Hello, I played around with the Zoom API and Zoom Engine API but did not find a way to trigger a redraw of the content. I tried to use ZoomEngine.setContentSize() and ZoomEngine.setContainerSize() in combination with View.invalidate() when changing the zoom level, but this does only scale the content and not trigger a redraw. 
@natario1 Could you point me in the right direction?

**Comment by natario1** [comment]
If it's an image you should use ZoomImageView instead of an image view inside a ZoomLayout.
If you can't do this, you could try setting `hasClickableChildren="true"` and see if that makes a difference.

**Comment by SilvanaP** [comment]
Thanks for the hint, I use a Zoomlayout and already have hasClickableChildren="true" set. My case is a bit tricky, I have a Zoom Layout with a FrameLayout inside. Inside the FrameLayout there are several Imageviews (they are stacked on each other and only one image view is visible at a time). I had a look at the ZoomEngine Code, but I am not sure when the actual first drawig pass with the contents in the Layout happens. Maybe retriggering that with new parameters would make the images crisp?

**Comment by SilvanaP** [comment]
Hello, I still face the same problem. Tried to set the minZoom to a high value (e.g 10) to force an initial draw that's crisp, but even then the image is pixelated. Any input on what else I could try?
