### ISSUE TITLE
latest version is wrong

### ISSUE THREAD

**Issue by milekey** [natario1/ZoomLayout#150]
The site's top banner and install guide indicate the latest version as 0.7.1 but it should be 1.7.1.

First I experienced an gradle error to use 0.7.1 then found that.

<img width="1269" alt="スクリーンショット 2020-05-12 14 42 52" src="https://user-images.githubusercontent.com/38986280/81643059-c10ed480-945f-11ea-95bb-18a11f2edf23.png">

**Comment by markusressel** [comment]
Thx for the info :+1:
@natario1 I would update it, but I don't have access to the documentation repo.

**Comment by natario1** [comment]
Yes nice catch. @markusressel docs are all in the docs folder actually, this should be in a file called config.yml. I'll fix it now

**Comment by markusressel** [comment]
Ah ok, thx for the info, I thought it was separate one.
