### ISSUE TITLE
ZoomImageView doesn't initially pan to center of the bitmap

### ISSUE THREAD

**Issue by King-Henry** [natario1/ZoomLayout#152]
- ZoomLayout 1.7.0/1
- Reproducible in official demo app: *Yes*
- Device / Android version: *Pixel, Android 10*

> For some reason when setting the image on the ZoomImageView, it doesn't pan to the center. It'll pan to the top, or bottom, but never the center regardless of what gravity or alignment I set.

> Currently the only way I can get it to center when initially setting the bitmap is to first call zoomImageView.setImageBitmap(bitmap) then set the pan to zoomImageView.panX / 2 and zoomImageView.panY / 2. This seems to work when the width and height of the content are bigger than the container(zoomImageView), however when either the width or height of the content is smaller than the container, the panx and pany both end up being 0, so this solution doesn't work. 

I recently opened a GitHub issue that ended up being closed as stale https://github.com/natario1/ZoomLayout/issues/135. Basically, I've gotten back to trying to repro the issue and now have a version of the sample app in which you'll be able to repro the issue.

https://github.com/King-Henry/ZoomLayout-Centering-Issue. This is the repository that contains the code to reproduce.

**Comment by markusressel** [comment]
Hey Henry, sorry for not getting back to you sooner.
I've had a quick look at your repository, very helpful :+1: 

First thing I noticed was this:
```xml
<com.otaliastudios.zoom.ZoomImageView
        android:id="@+id/zoom_image"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        [...]
```
The `0dp` height doesn't seem to work  correctly when using a `ConstraintLayout`, at least not on my device. The bottom of the image extends below the navigation bar and the overpan correction calculations are off, preventing the user to pan all the way to the bottom of the image. To work around this I just used `match_parent` for both `layout_width` as well as `layout_height`.

The second thing I noticed is the way your **CENTER PAN** button is implement **does not** pan the image to the center. As you can see in the documentation of the `panTo`:
```
Pans the content until the top-left coordinates match the given x-y values.
```
By using
```java
float x  = zoomImage.getEngine().getContentWidth();
float y  = zoomImage.getEngine().getContentHeight();
[...]
zoomImage.getEngine().panTo(-x/2, -y/2, false);
```
you are actually panning the top-left corner of the image to the center, which does **not** center the image inside of the `ImageView`. Have a look at #47 for a different approach to this.

However, you are right in that the image is not centered inside of the `ZoomLayoutView` when setting a new drawable. I have not found the issue yet though.

**Comment by markusressel** [comment]
Actually, the code proposed in #47 doesn't work for me, I used this instead:
```java
float zoomLayoutCenterX = (zoomImage.getEngine().getContainerWidth() / zoomImage.getRealZoom() / 2f);
float zoomLayoutCenterY = (zoomImage.getEngine().getContainerHeight() / zoomImage.getRealZoom() / 2f);
float contentCenterX = (zoomImage.getEngine().getContentWidth() / 2f);
float contentCenterY = (zoomImage.getEngine().getContentHeight() / 2f);
float diffX = contentCenterX - zoomLayoutCenterX;
float diffY = contentCenterY - zoomLayoutCenterY;
zoomImage.panTo(-diffX, -diffY, true);
```

Maybe @natario1 can tell if this is a good or bad way to do it.

**Comment by King-Henry** [comment]
Hey Markus,

I'm just now seeing the update on this issue 🤦 . But thank you for looking into the issue! I'm also happy to know that the repository was helpful for you. I tried to dig into the library to understand the issue but ended up being extremely confused. Thanks again!

**Comment by markusressel** [comment]
No problem, note that the fix has not been released yet, but it probably will in the coming days.
