### ISSUE TITLE
Disable Zoom

### ISSUE THREAD

**Issue by nikolamk** [natario1/ZoomLayout#16]
Is there any way to temporary pause ( disable ) ZoomLayout  from zoom and pinch? I want ZoomLayout  to stay at paused position until I resume it back  ( children  should keep listening their listeners) 

Thanks for this great component !

**Comment by natario1** [comment]
No. This goes along #15, we should add `zoomEnabled` , `verticalPanEnabled` and `horizontalPanEnabled` , both as XML attributes and methods.

**Comment by natario1** [comment]
This was fixed by #31
