### ISSUE TITLE
Set initial zoom, instead of pre-calculating to "fitCenter"

### ISSUE THREAD

**Issue by arecmetafora** [natario1/ZoomLayout#17]
Hi! A helpfull feature would be a method to set the initial scale applied to the image. I saw that after setting the image drawable, the initial zoom is computed to fit the parent`s dimension. However, using the scale type for the initial zoom would provide a better control of the image that is shown.

For instance, in my example I want to show the image "as is", with no automatic zoom.

I surpassed this limitation by adding these lines in the constructor

        // Set the min zoom to 1 to avoid the computed zoom to shrink my image
        getEngine().setMinZoom(1f, ZoomEngine.TYPE_REAL_ZOOM);
        getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                if(mOfflineMap != null && mOfflineMap.getMapBitmap() != null) {

                    // Compute the min zoom to fit the screen content
                    float minZoom = Math.min(
                            (float) getMeasuredWidth() / mOfflineMap.getMapBitmap().getWidth(),
                            (float) getMeasuredHeight() / mOfflineMap.getMapBitmap().getHeight());
                    getEngine().setMinZoom(minZoom, ZoomEngine.TYPE_REAL_ZOOM);

                    // Compute the actual zoom to the original zoom (no zoom at all)
                    getEngine().zoomTo(getEngine().getZoom() / getEngine().getRealZoom(), true);
                }
            }
        });

**Comment by natario1** [comment]
This will be possible in 1.2.0, see #28 . Thanks!
