### ISSUE TITLE
Android 6.0 Zoom bug with surface view.  Diagonal movement instead zoom

### ISSUE THREAD

**Issue by Yahor10** [natario1/ZoomLayout#173]
### Describe the bug
I override surface view(onTouch + scaleGesture) and zoom layout (dispatchTouchEvent)
Use 2 finger zoom(gesture).
Instead zooming it just moving view by diagonale with incorrect resizing.

- Library version: *Last*
- Reproducible in official demo app: *no*
- Device / Android version: *Sony,Huawei,Samsung, API 23*

### Expected behavior
Correct Zoom like in android 7.0 +
### XML layout
    <com.example.myapplication.view.MyZoomOverride
        android:id="@+id/zoomLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical|horizontal"
        app:animationDuration="280"
        app:flingEnabled="false"
        app:hasClickableChildren="true"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:maxZoom="2.2"
        app:maxZoomType="zoom"
        app:minZoom="0.55"
        app:minZoomType="zoom"
        app:overScrollHorizontal="true"
        app:overScrollVertical="true"
        app:verticalPanEnabled="true"
        app:horizontalPanEnabled="true"
        app:overPinchable="true"
        app:scrollEnabled="true"
        app:transformationGravity="center"
        app:alignment="center"
        app:transformation="none"
        app:threeFingersScrollEnabled="false"
        app:twoFingersScrollEnabled="true"
        app:oneFingerScrollEnabled="false"
        app:zoomEnabled="true">
        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">
    <com.example.myapplication.opengl.SurfaceView
        android:id="@+id/surface"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
       >
    </com.example.myapplication.opengl.SurfaceView>
        </androidx.constraintlayout.widget.ConstraintLayout>
    </com.example.myapplication.view.MyZoomOverride>
</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by markusressel** [comment]
Can you reproduce the behaviour when using the original classes, without method overrides?

**Comment by Yahor10** [comment]
Like i said:
"Reproducible in official demo app: no"
No its works fine

When i do pintch gesture in the center its start move to left up corner (zoom out) or to bottom right (zoom in) instead correct zooming

![dddd](https://user-images.githubusercontent.com/1306298/87025815-8ae19d00-c1e3-11ea-96c6-2a0334641652.PNG)

**Comment by markusressel** [comment]
Well, if you override the methods that handle touch input, and something breaks in the process, you broke something 😄 
We can't really help with that.

**Comment by Yahor10** [comment]
The problem is not in overrired methods 100%.
Firstly i remove override and the bug is still active....
Problem in somewhere else.

P.s android 7.0 works fine.
Android 6.0 without surface and with zoomlayout + simple view  works well

But Android 6.0 with surface and zoomlayout works bad

**Comment by natario1** [comment]
We have ZoomSurfaceView for this, see demo app.

**Comment by Yahor10** [comment]
ZoomSurfaceView from demo works ok , but with ZoomSurfaceView you  can not override render object and setup it with your app. Thats a problem. It throws exception because of that  setRenderer(this). When u trying set your custom render.

**Comment by natario1** [comment]
It should be used the way the demo app does - you don't write directly into the view with a renderer, instead you write _into_ its input surface. Then ZoomSurfaceView will do another render pass (from surface to screen) in which it applies zoom and pan values.

The input surface can be passed to video players, camera, ... or you can write directly into it with OpenGL.
