### ISSUE TITLE
AAPT: error: duplicate value for resource 'attr/maxZoom' with config ''.

### ISSUE THREAD

**Issue by SunitaMK** [natario1/ZoomLayout#176]
When i add zoom layout in my app I am getting below error

.gradle/caches/transforms-2/files-2.1/c136f2211885acf3b4676338cba8413d/jetified-zoomlayout-1.8.0/res/values/values.xml:3:5-55:25: AAPT: error: duplicate value for resource 'attr/maxZoom' with config ''.

**Comment by markusressel** [comment]
Did you try clearing the gradle cache?
