### ISSUE TITLE
recycleview + zoomlayout 

### ISSUE THREAD

**Issue by lan2000** [natario1/ZoomLayout#179]
recycleview + zoomlayout 

One item occupies one page in recycleview.
From the third item, ZoomLayout is invalid.
Can you help? Thank you
### Version used
1.8.0

**Comment by lan2000** [comment]
At this time   getZoom()=NaN

**Comment by markusressel** [comment]
Did you have a look at these issues?:
https://github.com/natario1/ZoomLayout/issues?q=is%3Aissue+recyclerview
