### ISSUE TITLE
ZoomLayout got stuck and not respond on any touch events.

### ISSUE THREAD

**Issue by ibnekhan** [natario1/ZoomLayout#18]
when ever i am panning and moving layout it got stuck most of the time, even i haven't implemented any click listeners on child views.

**Xml Usage**

 

<com.otaliastudios.zoom.ZoomLayout
        android:id="@+id/writeViewScroll"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        android:overScrollMode="always"
        app:hasClickableChildren="false"
        app:maxZoom="3"
        app:maxZoomType="zoom"
        app:minZoom="1"
        app:minZoomType="zoom"
        app:overPinchable="true"
        app:overScrollHorizontal="true"
        app:overScrollVertical="true">

  <FrameLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/writingLayout"
            android:layout_alignParentTop="true">

            <ImageView
                android:id="@+id/bgCardIv"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@color/colorAccent"
                android:scaleType="fitXY"
                android:src="@drawable/address" />

            <com.feltapp.writeview.components.WriteViewEdittext
                android:id="@+id/writeCardEt"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@android:color/holo_green_light"
                android:enabled="false"
                android:gravity="top|start"
                android:imeOptions="flagNoExtractUi"
                android:inputType="textMultiLine"
                android:padding="36dp" />

            <ImageView
                android:id="@+id/ivGuidlinesPreview"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:adjustViewBounds="true"
                android:scaleType="fitXY"
                android:src="@drawable/card"
                android:visibility="gone" />

        </FrameLayout>

 </com.otaliastudios.zoom.ZoomLayout>

**Comment by vixez** [comment]
Having this issues as well

**Comment by natario1** [comment]
I have no idea guys, does this happen within the demo app?

If it doesn't, please try to identify what you are doing in your app that causes the issue, so we can fix it or document it.
If it does... I would still ask you to do some debugging because I can't reproduce this.

Specifically, I would take a look at `ZoomLayout` parents which might be stealing touch events. For example, you can't put ZoomLayout in a scrollable container, it makes no sense.

**Comment by vixez** [comment]
Hello,
I have sent an email to you (mat.iavarone -AT- gmail.com). It includes the sample I'm working in and a brief explanation of the goal and how to simulate it touch stopping to work.

If you rather have me upload the files here that is fine as well.
This library seems like the only option I have to get the project to work, so I hope you can find what is going wrong because it looks like a great library!

Thanks in advance.
Glenn Ruysschaert

**Comment by natario1** [comment]
@vixez So you can't replicate in the demo app? I don't have much time these days, but I'll take a look when I find some

**Comment by vixez** [comment]
@natario1 it seems to lose the touch events in the demo app as well, but less frequent as the scrollable view is smaller. In the sample app I sent you the scrollable view is bigger and that's when it starts to go wrong (if you zoom in to maximum)

**Comment by vtminh** [comment]
I have same problem.
I also find the exact case that cause this problem. When disabling overScrollVertical, overScrollHorizontal and view is unable to drag (when view 's smaller than screen), if you try to drag, the view will not received any touch event after that. 
Now I'm not able to resolve that case, so I must **enable overScrollVertical and overScrollHorizontal.**

**Comment by vtminh** [comment]
I fixed this bug. 
In class **ZoomEngine** , method startFling(@ScaledPan int velocityX, @ScaledPan int velocityY), 
add  **setState(NONE);** to this line

<img width="175" alt="screen shot 2018-04-20 at 11 52 34 am" src="https://user-images.githubusercontent.com/20150782/39031269-5b660ac4-4491-11e8-8106-ff43e5a527bb.png">

**Comment by natario1** [comment]
That makes sense @vtminh ! Would you like to submit a PR?

**Comment by natario1** [comment]
Might also make sense to update to gradle plugin 3.X, android 27, `api` instead of `compile`, and so on... If you can't, no problem. Thanks for spotting the bug!

**Comment by natario1** [comment]
Fixed this in v1.1.1, thanks @vtminh for spotting!
