### ISSUE TITLE
How set zoom image view to FITXY scale

### ISSUE THREAD

**Issue by Yahor10** [natario1/ZoomLayout#187]
### How do I?
I have to setup image with zoom for full size screen(like launch screen), but with zooming...

How to correct configure size of zoomimage for fullscreen?

I need **Fullscreen zoomimageview**

As same as` <ImageView scaleType= "fitXY">` does.

Thanks
### Version used
latest

**Comment by markusressel** [comment]
Afaik this is not possible. The ZoomEngine does not provide this scale type, and honestly I don't think we should. 
I guess you will have to rescale your image manually to exactly fit the screen dimensions and then load it into `ZoomImageView` to get the desired effect.
