### ISSUE TITLE
Correct handle of large images more then standart imageview size

### ISSUE THREAD

**Issue by Yahor10** [natario1/ZoomLayout#192]
### How do I?
I have a bitmap (3000x4000) ,and i want to show it in ZoomImageView with full size and Center Crop . Without quallity loses ofcouse.

What i need to do for that?

I calculate relation between standart and large 2043/4000 = 0.51  and then call ` zoomLayout.zoomBy(0,51,true);`
Thanks for assistence

### Version used
Latest

**Comment by webserveis** [comment]
If your purpose is to make a gallery of images with zoom, better use Big ImageView https://github.com/Piasy/BigImageViewer
