### ISSUE TITLE
Change child container size while do zooming

### ISSUE THREAD

**Issue by Yahor10** [natario1/ZoomLayout#197]
### How do I?
I want to change size of the child view when zoom in event applied.
How it can be done properly?
```
void onChangedSize(){ // function must be called
}
```
### Version used
Latest

**Comment by markusressel** [comment]
You can add a `ZoomEngine.Listener` to the ZoomEngine to get updates when the internal matrix is updated (due to pan or zoom) and then maybe use `setContentSize` on the engine to change the dimensions? Not sure what your goal with this is though. Also note that this might cause an infinite loop.

**Comment by Yahor10** [comment]
I did it , its goes to infinite. Could you show working example?

**Comment by markusressel** [comment]
What is your goal with this? Why do you need this? Are you sure you need to do this?

I cannot think of a use case that requires what you are describing.

I think it is more helpful if you could provide an example of what you are trying to achieve first :smile:

**Comment by Yahor10** [comment]
Goal is to change surfaceview inside zoomlayout. 
I am using textures mipmapping or just HD images and i  want to change glViewPort with zoom for showing images with better quality.

**Comment by markusressel** [comment]
Are you using [ZoomSurfaceView](https://natario1.github.io/ZoomLayout/docs/zoom-surface)?

**Comment by Yahor10** [comment]
I am using ZoomContainer (ZoomLayout)
