### ISSUE TITLE
JCenter will shutdown on May 1st

### ISSUE THREAD

**Issue by PavloRatushnyi** [natario1/ZoomLayout#199]
Hey
JFrog announced that JCenter will shutdown on May 1st: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/. This means that this library won't be available from JCenter after that date. 
Will it be available on other repositories, like Maven Central?

**Comment by natario1** [comment]
That's not true, packages will be available until February 2022. But yes, we will migrate to Maven Central when needed.

**Comment by PavloRatushnyi** [comment]
Ok, thanks
