### ISSUE TITLE
layout directly zooms to max zoom

### ISSUE THREAD

**Issue by tusharshah1692** [natario1/ZoomLayout#205]
when app is opened the zoom layout directly zooms to max. How can we show normal view and zoom once touched
![screenshot-1626783913954](https://user-images.githubusercontent.com/82366772/126323469-8408aa66-e77f-4586-a21e-6fd025e5e41d.png)
![screenshot-1626783900030](https://user-images.githubusercontent.com/82366772/126323477-1a3264e1-dbc8-4d92-9016-26b6052d314b.png)

**Comment by markusressel** [comment]
You can use `app:transformation="centerInside"` to make the content fill up the whole screen, see:
https://natario1.github.io/ZoomLayout/docs/zoom-apis

**Comment by tusharshah1692** [comment]
> You can use `app:transformation="centerInside"` to make the content fill up the whole screen, see:
> https://natario1.github.io/ZoomLayout/docs/zoom-apis

did not work can directly make at min zoom by default when open the screen

**Comment by jerinamathews** [comment]
Am also facing this issue. Wehn the image is loaded it goes directly to max zoom. by default it should be in 1x scale right?

**Comment by markusressel** [comment]
Correct. If you can provide more info on this, please open a new issue so we can investigate it. Without an example setup it will be hard though.
