### ISSUE TITLE
Smooth animation into arbitrary  view point with zoomlayout

### ISSUE THREAD

**Issue by Yahor10** [natario1/ZoomLayout#207]
### Describe the bug
Animation pulls happens when i call  ` zoomLayout.moveTo(zoom,-xOffset,-yOffset,true)`.
Looks like it dodo X axis zoom then Y axis.  

Please add a clear description of what the bug is, **and** fill the list below.
- Library version: Last
- Reproducible in official demo app: *yes*
- Device / Android version: *Samsung,XIaomi,Huawei , API 27-30*

### To Reproduce
Steps to reproduce the behavior, possibly in the demo app:
Apply animation with X/Y offset into arbitrary point of an view or image.

### Expected behavior
Smooth works on the movement of the curve

### XML layout
Basic Image with ZoomLayout

**Comment by Yahor10** [comment]
Its reproduce often  with long animation ( more then 500ms )

**Comment by markusressel** [comment]
I think you mean the issue described in this one: #188
~~There has not been a solution to this (yet).~~
I thought this was fixed already. Maybe something else in an unusual configuration still triggers this. But we can discuss this in the mentioned issue.
