### ISSUE TITLE
ZoomLayout to Top

### ISSUE THREAD

**Issue by vtminh** [natario1/ZoomLayout#21]
Hello,
Firstly, thanks for good library. 
With my project requirement, I want to set zoomlayout to Top of screen, but the default config is center. Can you guide me how to set this? 
Thanks very much.

**Comment by natario1** [comment]
you can just panTo 0 to move everything to the top. 
The initial position is not very configurable at the moment, please subscribe to #17

**Comment by vtminh** [comment]
It doesn't work for me. 
Maybe you misunderstand my question. 
The default is: 
![1](https://user-images.githubusercontent.com/20150782/38479163-8282139e-3be7-11e8-894f-226c3998846c.jpg)
But, the possition i want: 
![2](https://user-images.githubusercontent.com/20150782/38479173-8e259f9a-3be7-11e8-8c03-5c5970f22285.jpg)

Hope you help me this case. 
Thanks.

**Comment by kumabook** [comment]
How about this?

`zoomLayout.setTransformation(TRANSFORMATION_CENTER_INSIDE, Gravity.TOP)`
