### ISSUE TITLE
RecyclerView zooming support

### ISSUE THREAD

**Issue by k-g-aleksandrov** [natario1/ZoomLayout#212]
When adding RecyclerView to existing ZoomLayout It works slow because recycler view is located inside of ZoomLayout's ScrollView. So whole recyclerview content is bound at the same time. 

So It would be great to have ZoomRecyclerView with same functionality as for ZoomLayout (with clickable children support).

**Comment by natario1** [comment]
I'd be happy to see a ZoomLayoutManager for recyclers, but I'm not sure if it's technically possible. If we don't bind the whole view, we won't know the full content size which currently is a fundamental information.
