### ISSUE TITLE
Min sdk version

### ISSUE THREAD

**Issue by moshtagh** [natario1/ZoomLayout#216]
minSdkVersion cannot be smaller than version 18 declared in library [com.otaliastudios.opengl:egloo:0.6.1]

**Comment by natario1** [comment]
We use egloo in ZoomSurfaceView. If you are not using ZoomSurfaceView, you can try to override the minSdkVersion using
 
`<uses-sdk tools:overrideLibrary="com.otaliastudios.opengl" />
`
In your manifest file.
