### ISSUE TITLE
touch move doesn't follow my finger exactly

### ISSUE THREAD

**Issue by mehrshad00** [natario1/ZoomLayout#219]
hello.
i set zoom 0.95 and create move code for one child in zoom layout but touch move doesn't follow my finger exactly.
how can fix it?

please help me!

### Version used
V 1.9.0

**Comment by SG-KiwanPark** [comment]
how about decrese duration?

setAnimationDuration(280)

**Comment by mehrshad00** [comment]
Thanks for answer. but not work!

**Comment by cristo1985** [comment]
@mehrshad00 ho do you solved for this NOT-WORKING-SHITTING-LIBRARY?
