### ISSUE TITLE
How to observe zoom or move callback?

### ISSUE THREAD

**Issue by SG-KiwanPark** [natario1/ZoomLayout#220]
### How do I?
Thanks for your hard work.

I want to know zoom level or panX, Y every after drag or pich zoom. But I don't know how to do.

If you have any idea?

Thank you again

### Version used
com.otaliastudios:zoomlayout:1.9.0

**Comment by anthonydelahoz** [comment]
You can use :

```
zoomLayout.getEngine().addListener(new ZoomEngine.Listener() {
            @Override
            public void onUpdate(@NonNull ZoomEngine zoomEngine, @NonNull Matrix matrix) {
                // zoomLayout.getZoom();
            }
            @Override
            public void onIdle(@NonNull ZoomEngine zoomEngine) {}
        });
```

**Comment by SG-KiwanPark** [comment]
> 당신이 사용할 수있는 :
> 
> ```
> zoomLayout.getEngine().addListener(new ZoomEngine.Listener() {
>             @Override
>             public void onUpdate(@NonNull ZoomEngine zoomEngine, @NonNull Matrix matrix) {
>                 // zoomLayout.getZoom();
>             }
>             @Override
>             public void onIdle(@NonNull ZoomEngine zoomEngine) {}
>         });
> ```

It works for me. Thank you

**Comment by waterdrake** [comment]
This works, but is there anyway to know if the zoom level was changed due to a touch event from a user versus it being set by other means?
