### ISSUE TITLE
Trouble by setting zoom programmatically

### ISSUE THREAD

**Issue by anthonydelahoz** [natario1/ZoomLayout#223]
Hello,

I use the zoomLayout.getEngine().addListener method to store in a preference the current zoom float value.
The goal is to set the zoom programmatically to the old state stored in the preference when opening again the Activity

I tried to call the zoomTo, zoomBy or realZoomTo methods but it doesn't works

Here my code on the onCreate() activity method :

```
zoomLayout = findViewById(R.id.zoom_layout);

// Retrieve a float value from the preferences.
// 1 = defValue – Value to return if this preference does not exist.
float getFloatZoomRoomPlan = LocalPreferenceManager.getInstance(ctx).getFloat(LocalPreferenceConstant.ZOOM_ROOM_PLAN, 1);

zoomLayout.zoomTo(getFloatZoomRoomPlan, false);
zoomLayout.zoomBy(getFloatZoomRoomPlan, false);
zoomLayout.realZoomTo(getFloatZoomRoomPlan, false);
```

Version used : 
com.otaliastudios:zoomlayout:1.9.0

**Comment by markusressel** [comment]
A couple of things to note:

* make sure you load the content of the ZoomLayout first
* make sure your stored value makes sense
* try the `moveTo` method instead and also pass a position

I am using the third approach [here](https://github.com/MkDocsEditor/MkDocsEditor-Android/blob/8ec613e141efb4216d4c2287f7581d5940b1f57a/app/src/main/java/de/markusressel/mkdocseditor/feature/editor/CodeEditorFragment.kt#L172) and it is working (note that this code doesn't use the ZoomLayout directly, but a `CodeEditorLayout` instead).

**Comment by anthonydelahoz** [comment]
Okay, i found the solution 👍 

`moveTo`, `zoomTo` and maybe others methods works only when using in `post `method :

```
zoomLayout.post(() -> {
    float getFloatZoomRoomPlan = 0.7f;
    zoomLayout.moveTo(getFloatZoomRoomPlan, 0, 0, false);
});
```
