### ISSUE TITLE
Build fails when float f-suffix is used in xml 

### ISSUE THREAD

**Issue by remiberthoz** [natario1/ZoomLayout#23]
The readme gives an example with:

    app:minZoom="0.7f"
    app:maxZoom="3f"

Which raises the building error:

    AGPBI: {"kind":"error","text":"error: \u00270.7f\u0027 is incompatible with attribute myPackage:minZoom (attr) float [weak].","sources":[{"file":"myFile","position":{"startLine":7}}],"original":"","tool":"AAPT"}

It's easily fixed with:

    app:minZoom="0.7"
    app:maxZoom="3"

**Comment by natario1** [comment]
Thank you @TiiXel , I have fixed this 👍
