### ISSUE TITLE
Zoom listener

### ISSUE THREAD

**Issue by shykero** [natario1/ZoomLayout#25]
Is there any way to listen scroll changes?

**Comment by AlvaroFalcon** [comment]
Actually, if you want to listen to Zoom changes, there is a "hack" I'm currently using.

You could add a pinch listener to the layout, so you know when pinch is detected, there must be a zoom change.

```
    private inner class PinchListener : ScaleGestureDetector.SimpleOnScaleGestureListener() {

        override fun onScale(detector: ScaleGestureDetector): Boolean {
            //Your code
            return true
        }
    }
```

**Comment by shykero** [comment]
Thanks Alvaro. I find another solution. I've extended from **ZoomLayout** class and override method **onIdle**.

That's my code:

public class CustomZoomLayout extends ZoomLayout {

    private ZoomListener mListener;

    public CustomZoomLayout(@NonNull Context context) {
        super(context);
    }

    public CustomZoomLayout(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
    }

    public CustomZoomLayout(@NonNull Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    public void onIdle(ZoomEngine engine) {
        if (mListener!=null) mListener.onZoomIdle(engine.getZoom());
        super.onIdle(engine);
    }

    public void setListener(ZoomListener mListener) {
        this.mListener = mListener;
    }

    public interface ZoomListener {
        void onZoomIdle(float currentZoom);
    }
}


Method **onIdle** called after the user has finished scaling the picture. Then I just call method onZoomIdle(..) of ZoomListener. 

CustomZoomLayout I'm using in fragment layout file.
