### ISSUE TITLE
Convert code to Kotlin

### ISSUE THREAD

**Issue by markusressel** [natario1/ZoomLayout#36]
Hey, I really dig this library and would love to see it come to life in Kotlin.
I know you said you would migrate this library to Kotlin in the long run (https://github.com/natario1/ZoomLayout/issues/2).

I would like to take the chance and convert the existing code to a version that is usable for both Kotlin and Java.

**Comment by natario1** [comment]
Sure, let's do it!

**Comment by markusressel** [comment]
Since #38 is now merged this issue is closed. For any kotlin related changes please create a new issue.
