### ISSUE TITLE
Sometimes pan with 1 finger is not working

### ISSUE THREAD

**Issue by kuoliangkwong** [natario1/ZoomLayout#41]
I added a custom sticker view inside ZoomLayout. Sometime the panning not working as depicted in the gif below

![20180628_113622](https://user-images.githubusercontent.com/8188634/42011968-92bfbbec-7ac8-11e8-96c1-90419ee32a51.gif)

It works perfectly when using 2 fingers panning

**Comment by KoTius** [comment]
I experienced same problem. Occurs if you double tap at layout (tapping to fast). Second tap won't allow you to pan

**Comment by yaraht17** [comment]
I have same problem.  Do you have solution?

**Comment by Yundin** [comment]
I fixed it by removing OnDoubleTapListener here #56

**Comment by markusressel** [comment]
Since this should be fixed I'm closing this issue.
Feel free to reopen if the issue pops up again.
