### ISSUE TITLE
minSdkVersion 16?

### ISSUE THREAD

**Issue by Naguchennai** [natario1/ZoomLayout#44]
minSdkVersion 16? lol i missed lot off mobile phone and client ... why this?????? i think 14 is ok .. this lib no need minSdkVersion 16...

**Comment by natario1** [comment]
I'm pretty sure that the 16 was not chosen randomly... I don't remember why though.

**Comment by markusressel** [comment]
According to Google only a mere 0.5% of Android users are still using a Version below 4.1 (which is API Level 16). Supporting 99.5% of all Android users imo is more than a good tradeoff between platform features and compatibility.

![image](https://user-images.githubusercontent.com/14024504/43411681-384a0646-942b-11e8-91b3-702abcc61628.png)
