### ISSUE TITLE
Need protip: how to panTo zoomed view to specific point? (10% for example)

### ISSUE THREAD

**Issue by Svoka** [natario1/ZoomLayout#47]
Hi! Can't figure it out which params I need to use to calculate panTo values?

Size of the screen and realSize of the view?

**Comment by natario1** [comment]
Just the size of your content, in pixels.

If using ZoomLayout, it's the layout_width and layout_height of the view that you have put inside it. 
If using ZoomImageView, it's the drawable size.

Note that a positive translation will move the content down/right. So depending on your case, you might need to use negative values.

**Comment by Svoka** [comment]
Hm, 
here is my code

` panX = -(l_content.width  / 2).toFloat()

 panY = -(l_content.height  / 2).toFloat()

zm_zoom.engine!!.moveTo(zoom, panX, panY, false)`

I'm expect content to be zoom on the center of the screen, but it's just on the right/bottom position,
do I miss something?

**Comment by natario1** [comment]
This will move the center of the content to the top-left corner of ZoomLayout
(assuming it is possible at the given zoom level. We never allow empty space on more than 2 sides)

**Comment by natario1** [comment]
Something like this might work.

```kotlin
val zoomLayoutCenterX = (zoomLayout.width / 2).toFloat()
val zoomLayoutCenterY = (zoomLayout.height / 2).toFloat()
val contentCenterX = (content.width / 2).toFloat()
val contentCenterY = (content.height / 2).toFloat()
val diffX = contentCenterX - zoomLayoutCenterX
val diffY = contentCenterY - zoomLayoutCenterY
zoomLayout.panTo(-diffX, -diffY, true)
```

Anyway everything is possible, it just takes some logic.

**Comment by Svoka** [comment]
@natario1 thanks! I knew i need the part with screen size (zoomLayout.width in your example)
