### ISSUE TITLE
How to scroll inside ZoomLayout ?

### ISSUE THREAD

**Issue by adityasonel** [natario1/ZoomLayout#50]
I am trying to put a ScrollView inside a ZoomLayout, but ScrollView is not working. And that's my question how to Scroll inside ZoomLayout ?

**Comment by natario1** [comment]
What is a scroll bar? You scroll ZoomLayout with your finger or with the pan* methods.

**Comment by adityasonel** [comment]
Sorry it is ScrollView not ScrollBar. Yeah you are right, but I have a list of items in ZoomView, and I want scroll the list but I know touch event is taking by ZoomView. So is there any way to put list in ZoomView ?

**Comment by natario1** [comment]
A ScrollView for your content? Just remove it! Use a LinearLayout with wrap_content.

ZoomLayout is just a better ScrollView.

**Comment by markusressel** [comment]
I think the main issue people run into (when reading this) is passing touch events to ZoomLayout children even when pan/zoom gestures are used. Imo this should not be a focus of this library as it obviously causes issues with overlapping gesture detections within the view which will always lead to bad UX.
@natario1 closing this issue for the mentioned reasons and you already provided a solution.
