### ISSUE TITLE
Unable to interrupt Pan

### ISSUE THREAD

**Issue by Tadaboody** [natario1/ZoomLayout#61]
### Steps to produce:
1. Pan fast
2. Press view to stop panning
### Excepted behaviour:
- Pan immediately stops, and the view isn't tapped
### Current behaviour:
- Nothing, the pan just continues and doesn't respond to tap

**Comment by natario1** [comment]
Thank you, it doesn't work indeed

**Comment by Tadaboody** [comment]
Now that #38 is merged I feel more confident trying to tackle this - expect an early PR this week

**Comment by markusressel** [comment]
Is this a bug introduced by #38?

**Comment by Tadaboody** [comment]
@markusressel No but I wanted to wait for it to be merged because I prefer to work on Kotlin

**Comment by Tadaboody** [comment]
Completely forgot about this so sorry 🙏 thanks for the fix @markusressel

**Comment by markusressel** [comment]
@Tadaboody no problem, hope it works :smile:
