### ISSUE TITLE
default zoom coordinate

### ISSUE THREAD

**Issue by kev7037** [natario1/ZoomLayout#63]
Hi
I'm using `tablview `inside of the `zoomView `. The problem is that by default, zoom view shows middle rows of the table -horizontally and vertically center-. any way to show top of the table by default?

**Comment by DennisBlock** [comment]
You have to set `app:transformationGravity` to `top`. You can read more about this in the [Transformations](https://github.com/natario1/ZoomLayout#transformations) section in the README.

**Comment by markusressel** [comment]
Thx @DennisBlock for helping the community :+1: :nerd_face:
