### ISSUE TITLE
Zoom and Pan to coordinates

### ISSUE THREAD

**Issue by RobertoBrocca** [natario1/ZoomLayout#77]
Hi,

I have a ScrollView as parent, its child is a LinearLayout that contains the ZoomLayout. 
The ZoomLayout contains a FrameLayout with an ImageView and another FrameLayout that contains some EditTexts.

I implemented this complex structure to create a PDF compiler. The ImageView will contains the PDF image and, above of it, I have a FrameLayout that has some Edittexts placed with particular coordinates.

I need to "jump" from an EditText to another one (with a Button), applying zoom and pan to the interested EditText. 

I tried to implement the method "moveTo" of the class ZoomLayout passing the zoom value, my Edittext coordinates (x and y) and the animated value (boolean).
I haven't the expected result because my layout moves to wrong coordinates.

This is my structure:

<ScrollView>
	<LinearLayout>
		<ZoomLayout>
			<FrameLayout>
				<ImageView/> 
				<FrameLayout>
					<EditText/>
					<EditText/>
					<EditText/>
					...
				</FrameLayout>
			</FrameLayout>
		</ZoomLayout>
	</LinearLayout>
</ScrollView>

Please, help me and sorry for my bad english

**Comment by RobertoBrocca** [comment]
`

<RelativeLayout>

	<ScrollView>

		<LinearLayout>
	
			<ZoomLayout>

				<FrameLayout>

					<ImageView/> 

					<FrameLayout>

						<EditText/>
						<EditText/>
						<EditText/>
						...

					</FrameLayout>
			
				</FrameLayout>

			</ZoomLayout>

		</LinearLayout>

	</ScrollView>

</RelativeLayout>

`

**Comment by RobertoBrocca** [comment]
Moreover, the scroll of the parent ScrollView combined with horizontal and vertical scroll of the ZoomLayout causes me some problem, so pinch zoom is not very comfortable.. How can I solve this other problem?

**Comment by markusressel** [comment]
> I tried to implement the method "moveTo" of the class ZoomLayout passing the zoom value, my Edittext coordinates (x and y) and the animated value (boolean).
> I haven't the expected result because my layout moves to wrong coordinates.

Make sure to use negative values for x and y. See [the Pan section of the README](https://github.com/natario1/ZoomLayout#pan).

> Moreover, the scroll of the parent ScrollView combined with horizontal and vertical scroll of the ZoomLayout causes me some problem, so pinch zoom is not very comfortable.. How can I solve this other problem?

I **strongly** advise against nesting views that use the same kind of gestures. This not only leads to software problems but also to bad UX. If you can try to move the `ZoomLayout` to another screen where it is independent from the `ScrollView`.

If this is not an option you can try using [NestedScrollView](https://developer.android.com/reference/androidx/core/widget/NestedScrollView) instead of your `ScrollView`.

**Comment by RobertoBrocca** [comment]
Giving negative values to x and y, I solved problems for X coordinates, now I have the correct position for X coordinate. But I don't get always the correct placement for the Y coordinate. For example, if a scroll down to the bottom of my PDF image, if I try to go to the previous EditText, placed on the middle of the ZoomLayout, I don't see my EditText and I need to scroll up to it manually. Could it be caused by the parent ScrollView?

I've already tried to use NestedScrollView instead of ScrollView, but there are not beneftis. If you confirm me that there are not solutions to use a ScrollView as a parent, I'll try to find an alternative way.

Thank you for the support!

**Comment by natario1** [comment]
You could try disabling vertical pan in ZoomLayout. But I'm not sure it will work correctly either

**Comment by RobertoBrocca** [comment]
@natario1 I've already tried disabling vertical pan, but it doesn't solve all my problems

**Comment by RobertoBrocca** [comment]
@markusressel I removed the parent ScrollView. Now X and Y coordinates are exact, positioning works as well, but I have the last problem:

If I have an EditText placed on the bottom of the ImageView, when it requests focus, keyboard cover it and I can't scroll (with vertical pan) down to my interested EditText. That's why I added the ScrollView as a parent.

I can solve this problem in another way?

**Comment by markusressel** [comment]
Well I would think that this has to do with how the activity reacts to the soft-keyboard.
Have a look at the android `manifest.xml` activity property [android:windowSoftInputMode](https://developer.android.com/guide/topics/manifest/activity-element#wsoft)

**Comment by RobertoBrocca** [comment]
I've tried using both adjustPan and adjustResize, but I didn't get change.. my ZoomLayout is covered by keyboard and not pushed up.

**Comment by RobertoBrocca** [comment]
I solved the problem using match_parent for the height of ZoomLayout (before, I gave a dynamic height programmatically).
Thank you very much :D

**Comment by markusressel** [comment]
Glad you got it working :+1:
I'm closing this for now, feel free to reopen or create a new issue if anything comes up.
