### ISSUE TITLE
Disabled pan consumes drag gesture

### ISSUE THREAD

**Issue by nil2l** [natario1/ZoomLayout#78]
Even if both pan are disabled `ZoomEngine` still consumes drag event (single pointer) though doesn't use it. So children can't get it to detect drag gesture as they receive `ACTION_CANCEL` because of `onInterceptTouchEvent` returning `true`.

**Comment by markusressel** [comment]
Thx for your interest! Looks good :+1:
Can you create a PR for this?

**Comment by markusressel** [comment]
Ah you already did :smile: thx!

**Comment by nil2l** [comment]
Yes, I thought github will bind them automatically as branch name and commit comment have `#78` ref.

**Comment by markusressel** [comment]
You have to reference it in the PR description, then it will work :blush:
