### ISSUE TITLE
Create ZoomSurfaceView

### ISSUE THREAD

**Issue by kevin4dhd** [natario1/ZoomLayout#88]
I have tried in many ways to use SurfaceView with ZoomLayout, I would like to know if it is possible to use it, thanks.

**Comment by natario1** [comment]
You can use a GLSurfaceView, do the drawing in openGL and use a ZoomEngine (not ZoomLayout) to compute the transformation matrix.

Not easy but possible. It is my plan to do so in this library one day (create a ZoomSurfaceView)

**Comment by kevin4dhd** [comment]
It would be perfect if you create Zoom SurfaceView, but is there an example of how to implement ZoomEngine? I have read the documentation but I have no idea how to combine GLSurfaceView with ZoomEngine, if you give me an example I would be more than grateful to you

**Comment by natario1** [comment]
I have no resources at hand, sorry. I am also very busy to work on ZoomSurfaceView at the moment, but I will do at some point.

**Comment by kevin4dhd** [comment]
I'll wait for ZoomSurfaceView to come out, thank you very much.

**Comment by natario1** [comment]
Cool. Will make this thread a feature request.

This will make it possible to add ZoomEngine functionality to camera preview or video streams.
