### ISSUE TITLE
Zoom not animated

### ISSUE THREAD

**Issue by asclepix** [natario1/ZoomLayout#91]
I'm using `zoomBy` and `moveTo` with the animation parameter set to `true`. I've tried my app on 4 different devices, but I see the animation only on one of them, while on the others there is no animation. How can I improve this situation? (I've tried to increase `animationDuration`, but without success).

**Comment by asclepix** [comment]
Sorry, I discover that the animation doesn't works on devices on which I disabled animation (Window animation scale, Transition animation scale and Animator duration scale - for instrumented tests), while works on deveices with animations enabled.

**Comment by natario1** [comment]
Cool!
