### ISSUE TITLE
Could not resolve ZoomLayout 1.5.1

### ISSUE THREAD

**Issue by asclepix** [natario1/ZoomLayout#95]
I've updated dependencies to `implementation 'com.otaliastudios:zoomlayout:1.5.1'`, but I've got:

`ERROR: Unable to resolve dependency for '...': Could not resolve com.otaliastudios:zoomlayout:1.5.1.`

I think the issue comes from `libVersion = '1.5.0'` in the `build.gradle` so that in the _zoomlayout-1.5.1.pom_ file there is:

`<version>1.5.0</version>`

Thank you

**Comment by natario1** [comment]
Ops! Thanks, I have fixed this, please try again
