### ISSUE TITLE
Any reason, we measure child to size 0

### ISSUE THREAD

**Issue by xiaogegexiao** [natario1/ZoomLayout#98]
Hi 
I am currently reading the zoom layout code
in onMeasure of `ZoomLayout`

```
// Measure ourselves as MATCH_PARENT
        val widthMode = View.MeasureSpec.getMode(widthMeasureSpec)
        val heightMode = View.MeasureSpec.getMode(heightMeasureSpec)
        if (widthMode == View.MeasureSpec.UNSPECIFIED || heightMode == View.MeasureSpec.UNSPECIFIED) {
            throw RuntimeException("$TAG must be used with fixed dimensions (e.g. match_parent)")
        }
        val widthSize = View.MeasureSpec.getSize(widthMeasureSpec)
        val heightSize = View.MeasureSpec.getSize(heightMeasureSpec)
        setMeasuredDimension(widthSize, heightSize)

        // Measure our child as unspecified.
        val spec = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED)
        measureChildren(spec, spec)
```

May I ask why do we measure child to 0 size

Thanks #

**Comment by natario1** [comment]
The content size should not depend on the container size, so we pass 0-UNSPECIFIED - this way the content View will measure itself as WRAP_CONTENT and have its own dimensions without parent constraints

**Comment by xiaogegexiao** [comment]
Thanks @natario1 , as I run into a case that I want the content to be match parent and be `centerInside` that I customised the `ZoomLayout` a little bit on the `onMeasure` to measureChildren to match parent.

However! I found that the `ZoomLayout` already supports making the child content to match parent when we set the `minZoom` to `1`. So, I don't need to customise that which is awesome.

Another question may not be related to this topic is that, I used the ZoomLayout, it seems not working very well in recyclerview viewholder. But it works with Android Pager which is very interesting. Just wondering how you think on this?

**Comment by natario1** [comment]
You don't need to customize that typically, you would use wrap_content and set the ZoomLayout transformation to CENTER_INSIDE.

I have never tried to use ZL in a RecyclerView. If you can provide a demo app we can take a look. But most likely this is not supported

**Comment by xiaogegexiao** [comment]
Thanks @natario1 . 

For having ZL in RecyclerView, I create a branch on my git repo. 

https://github.com/xiaogegexiao/ZoomLayout/tree/experimental/xiao/zoomlayout-in-recyclerview.

You can take a look when you have time

**Comment by markusressel** [comment]
@xiaogegexiao So looking at your branch... it just works?
I don't see any code changes besides the demo app stuff.
So we can close this issue?

**Comment by xiaogegexiao** [comment]
@markusressel Yeah, thanks, I think it works. Just wonder whether it will support ZL in recyclerview. I will close this issue.
