### ISSUE TITLE
Using this with a TextureView

### ISSUE THREAD

**Issue by HBiSoft** [natario1/ZoomLayout#99]
I'm using a `TextureView` to display a video,  inside `onMeasure` I scale the view and maintain the aspect ratio of the video. 

Will I be able to place my `TextureView` inside a ZoomLayout?

**Comment by natario1** [comment]
Placing the `TextureView` inside a `ZoomLayout` should work!

But it would be more efficient if you create a `TextureView` subclass, use `ZoomEngine` in it (take a look at ZoomImageView for reference), and when you get the engine matrix, use `textureView.setTransform()`.

A `ZoomTextureView` would be a cool addition to the project

**Comment by natario1** [comment]
You can see an example of zoomable video inside the demo app, using ZoomSurfaceView

**Comment by HBiSoft** [comment]
I ended up creating my own zoom function. It would be great if this library has a `ZoomTextureView` out the box, but I understand that it will not work in some situations, like when the user has multiple `TextureView`'s.
